# Generated by Django 3.2.4 on 2021-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormationCrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='etat',
            field=models.CharField(choices=[('active', 'Active'), ('non', 'Desactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='formation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
